In [1]:
import numpy as np

a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [8]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)


tic = time.time()

c = np.dot(a,b)

toc = time.time()


print(1000*(toc- tic))


tic = time.time()
c = 0
for i in range(1000000):
    c += a[i]*b[i]
    
toc = time.time()


print(1000*(toc- tic))



1.8999576568603516
799.8244762420654


In [7]:
722/2

361.0

In [12]:
A = np.array([[56, 0, 4.4, 68],
               [1.2,104, 52, 8],
             [1.8,135,99,0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [26]:
print(np.sum(A,axis = 0))

[ 59.  239.  155.4  76.9]


In [25]:
print(A[1]*100/np.sum(A,0))

[ 2.03389831 43.51464435 33.46203346 10.40312094]


In [27]:
print(A*100/np.sum(A,0))

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [28]:
A + 2

array([[ 58. ,   2. ,   6.4,  70. ],
       [  3.2, 106. ,  54. ,  10. ],
       [  3.8, 137. , 101. ,   2.9]])

In [29]:
assert(A.shape == (5,1))

AssertionError: 